{ lib, den, ... }:
{
  den.aspects.tmux = {
    tmux = { pkgs, ... }: {
      plugins = {
        sensible = {
          package = pkgs.tmuxPlugins.sensible;
          source = "share/tmux-plugins/sensible/sensible.tmux";
        };

        resurrect = {
          package = pkgs.tmuxPlugins.resurrect;
          source = "share/tmux-plugins/resurrect/resurrect.tmux";
          init = ''
            set -g @resurrect-capture-pane-contents 'on'
            set -g @resurrect-strategy-nvim 'session'
          '';
          after = [ "sensible" ];
        };

        continuum = {
          package = pkgs.tmuxPlugins.continuum;
          source = "share/tmux-plugins/continuum/continuum.tmux";
          init = ''
            set -g @continuum-restore 'on'
            set -g @continuum-save-interval '1'
            set -g @continuum-boot 'off'
            set -g @continuum-systemd-start-cmd 'new-session -Ad -s default'
          '';
          after = [ "resurrect" ];
        };
      };

      initConfig = ''
        # Base options
        set -g mouse on
        set -g mode-keys vi
        set -g base-index 1
        setw -g pane-base-index 1
        set -g renumber-windows on
        set -g history-limit 50000

        # Window and pane splitting
        bind | split-window -h
        bind - split-window -v
        unbind '"'
        unbind %

        # Status bar
        set -g status-position bottom
        set -g status on
        set -g status-interval 15
        set -g status-left "#[fg=white,bold] #S"
        set -g status-right "#[fg=green] #(whoami)@#H"
        set -g status-style "bg=default"
        set -g status-justify absolute-centre
        set -g status-left-length 50
        set -g window-status-separator ""
        set -g window-status-format "#[fg=gray]  #I:#W  "
        set -g window-status-current-format "#[fg=cyan,bold]  #I:#W  "

        # Open new panes/windows in current directory
        bind c new-window -c "#{pane_current_path}"
        bind '"' split-window -c "#{pane_current_path}"
        bind % split-window -h -c "#{pane_current_path}"

        # New session with current directory name and switch
        bind C-s run-shell "tmux new-session -d -s \"$(basename #{pane_current_path})\" -c \"#{pane_current_path}\" \; switch-client -t \"$(basename #{pane_current_path})\""

        # Repeatable movement/swapping (using prefix)
        # Swap panes
        bind -r H swap-pane -U
        bind -r L swap-pane -D
        # Swap windows
        bind -r J swap-window -t -1
        bind -r K swap-window -t +1

        # Repeatable navigation
        # Navigate panes
        bind -r h select-pane -L
        bind -r j select-pane -D
        bind -r k select-pane -U
        bind -r l select-pane -R
        # Navigate windows
        bind -r p previous-window
        bind -r n next-window
      '';
    };

    user = {
      linger = true;
    };
  };

  den.schema.user.includes = [
    ({ user }:
      den.batteries.forward {
        each = lib.singleton user;
        fromClass = _: "tmux";
        intoClass = _: "hjem";
        intoPath = _: [ "tmux" ];
        fromAspect = u: u.aspect;
        adaptArgs = args: { inherit (args) pkgs; };
      })
  ];

  den.default.nixos.hjem.extraModules = lib.mkAfter [
    ({ inputs, lib, config, pkgs, ... }:
      let
        dag = inputs.dag.lib { inherit lib; };

        renderPlugin = p:
          ''
            ${lib.optionalString (p.init != "") p.init}
            ${lib.concatStringsSep "\n" (
              map (s: "run-shell '${p.package}/${s}'") (lib.optional (p.source != null) p.source ++ p.sources)
            )}
          '';

        toDagEntry = name: p: {
          inherit name;
          value = dag.entryAfter p.after (renderPlugin p);
        };

        renderPluginDag = plugins:
          dag.render {
            entries = lib.listToAttrs (lib.mapAttrsToList toDagEntry plugins);
          };

        tmuxConf = pkgs.writeText "tmux.conf" ''
          # Generated by nix-config - do not edit.
          ${config.tmux.initConfig}

          # Plugins
          ${renderPluginDag config.tmux.plugins}
        '';

        tmuxRestoreSession = pkgs.writeShellApplication {
          name = "tmux-restore-session";
          runtimeInputs = [
            pkgs.coreutils
            pkgs.gawk
            pkgs.gnugrep
            pkgs.gnused
            pkgs.tmux
          ];
          text = ''
            tmux_config="$HOME/.config/tmux/tmux.conf"
            resurrect_last="$HOME/.tmux/resurrect/last"
            resurrect_restore="${pkgs.tmuxPlugins.resurrect}/share/tmux-plugins/resurrect/scripts/restore.sh"

            if tmux has-session 2>/dev/null; then
              exit 0
            fi

            tmux -f "$tmux_config" new-session -d

            if [ -e "$resurrect_last" ]; then
              "$resurrect_restore" || true
            fi

            if tmux has-session -t 0 2>/dev/null; then
              tmux rename-session -t 0 default
            fi

            if ! tmux has-session 2>/dev/null; then
              tmux -f "$tmux_config" new-session -Ad -s default
            fi
          '';
        };

        pluginSubmodule = lib.types.submodule {
          options = {
            package = lib.mkOption {
              type = lib.types.package;
              description = "Package containing plugin scripts.";
            };

            source = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              description = "Single plugin script path inside the package.";
            };

            sources = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
              description = "Ordered plugin script paths inside the package.";
            };

            init = lib.mkOption {
              type = lib.types.lines;
              default = "";
              description = "Tmux commands run before plugin scripts.";
            };

            after = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
              description = "Plugin names that must load before this plugin.";
            };
          };
        };
      in
      {
        options.tmux = {
          plugins = lib.mkOption {
            type = lib.types.attrsOf pluginSubmodule;
            default = { };
            description = "Tmux plugins rendered into tmux.conf.";
          };

          initConfig = lib.mkOption {
            type = lib.types.lines;
            default = "";
            description = "Tmux configuration emitted before rendered plugins.";
          };
        };

        config = {
          files.".config/tmux/tmux.conf".source = tmuxConf;
          packages = [ pkgs.tmux ];
          systemd.services.tmux-default-session = {
            description = "Tmux default session";
            wantedBy = [ "default.target" ];
            serviceConfig = {
              Type = "oneshot";
              ExecStart = lib.getExe tmuxRestoreSession;
              RemainAfterExit = true;
            };
          };
        };
      })
  ];
}
